package com.frstassign.airquality;

// Generated by Selenium IDE

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.CoreMatchers.containsString;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import org.openqa.selenium.Dimension;

import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.web.server.LocalServerPort;

import io.github.bonigarcia.seljup.SeleniumExtension;

import org.openqa.selenium.JavascriptExecutor;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ExtendWith(SeleniumExtension.class)
public class Proj1tryTest{
  private WebDriver driver;
 // private Map<String, Object> vars;
  JavascriptExecutor js;

  @LocalServerPort
  private int port;

  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    //vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void goodCity() {
    driver.get("http://localhost:" + port+'/');
    driver.manage().window().setSize(new Dimension(1853, 895));
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("porto");
    driver.findElement(By.name("submit")).click();
    String info = driver.findElement(By.cssSelector("textarea")).getText();
    assertThat(info, containsString("Air Quality:"));
  }

  @Test
  public void bafCity() {
    driver.get("http://localhost:" + port+'/');
    driver.manage().window().setSize(new Dimension(1853, 895));
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("portsbcaskcs");
    driver.findElement(By.name("submit")).click();
    String info = driver.findElement(By.cssSelector("textarea")).getText();
    assertThat(info, containsString("Bad Name"));
  }

  @Test
  void testWithOneChrome() {
      driver.get("http://localhost:" + port+'/');
      assertThat(driver.getTitle(),
              containsString("airquality"));
  }
}
